apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwTest1233
  labels:
    app: fwTest1233
  namespace: namespace-workflow-1686859141057
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwTest1233
  template:
    metadata:
      labels:
        app: fwTest1233
    spec:
      containers:
        - name: fwTest1233
          image: fwtest22.azurecr.io/image-workflow-1686859141057:latest
          ports:
            - containerPort: 3000