apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwTest12333
  labels:
    app: fwTest12333
  namespace: namespace-workflow-1686858667931
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwTest12333
  template:
    metadata:
      labels:
        app: fwTest12333
    spec:
      containers:
        - name: fwTest12333
          image: fwTest456registry.azurecr.io/image-workflow-1686858667931:latest
          ports:
            - containerPort: 3000