apiVersion: v1
kind: Service
metadata:
  name: fwTest12333
  namespace: namespace-workflow-1686858667931
spec:
  type: LoadBalancer
  selector:
    app: fwTest12333
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000